import { Film, FolderOpen, Grid2X2, Settings2 } from "lucide-react";

type Project = { id: string; title: string; sceneCount: number; duration: string; status: string; progress: number; updated: string; image: string };

export default function WorkspaceView({ section, projects, onOpenProject, onNewProject }: { section: "Projects" | "Media" | "Templates" | "Settings"; projects: Project[]; onOpenProject: (id: string) => void; onNewProject: () => void }) {
  const config = { Projects: [FolderOpen, "Your projects", "Open a project to resume its production plan."], Media: [Film, "Media library", "Completed Google Flow clips and uploaded source media will appear here."], Templates: [Grid2X2, "Production templates", "Reusable style bibles, camera language, and pacing presets will live here."], Settings: [Settings2, "Workspace settings", "Configure your workspace preferences and production defaults."] } as const;
  const [Icon, title, description] = config[section];
  return <section className="workspace-view"><div className="workspace-view__hero"><div className="workspace-view__icon"><Icon size={24} /></div><div><p className="dashboard-eyebrow">WORKSPACE / {section.toUpperCase()}</p><h1>{title}</h1><p>{description}</p></div>{section === "Projects" && <button className="dashboard-primary-button" type="button" onClick={onNewProject}>New project</button>}</div>{section === "Projects" ? <div className="workspace-project-grid">{projects.map((project) => <button className="workspace-project-card" type="button" key={project.id} onClick={() => onOpenProject(project.id)}><img src={project.image} alt="" /><span><strong>{project.title}</strong><small>{project.sceneCount} scenes · {project.duration} · {project.updated}</small><b>{project.status} · {project.progress}%</b></span></button>)}</div> : <div className="workspace-placeholder"><Icon size={28} /><strong>{section} is ready for the next production module.</strong><p>The destination now opens correctly. Its data module can be expanded without changing the main dashboard.</p></div>}</section>;
}
