import { Check, Clock3, Film, Save } from "lucide-react";
import { toast } from "sonner";

export type TimelineItem = { id: string; sceneId: string; sceneNumber: number; startTimeSeconds: number; endTimeSeconds: number; clipUrl: string; speed: number; transition: string; caption: string; soundEffect: string };

function time(value: number) { return `${Math.floor(value / 60).toString().padStart(2, "0")}:${Math.floor(value % 60).toString().padStart(2, "0")}`; }

export default function TimelineAssembly({ timeline, approved, canPrepare, preparing, saving, onPrepare, onChange, onSave }: { timeline: TimelineItem[]; approved: boolean; canPrepare: boolean; preparing: boolean; saving: boolean; onPrepare: () => void; onChange: (timeline: TimelineItem[]) => void; onSave: (approved: boolean) => void }) {
  function update(id: string, field: keyof TimelineItem, value: string | number) { onChange(timeline.map((item) => item.id === id ? { ...item, [field]: value } : item)); }
  async function preview(url: string) { if (!url) return; window.open(url, "_blank", "noopener,noreferrer"); }
  return <section className="timeline-panel"><div className="timeline-panel__header"><div><p className="dashboard-eyebrow">TIMELINE ASSEMBLY</p><h2>Match the clips to the narration.</h2><p>Completed Google Flow clips are placed on the audio timing spine. Adjust the edit before sending it to render.</p></div><div className="timeline-actions"><button className="secondary-action-button" type="button" disabled={!canPrepare || preparing} onClick={onPrepare}><Clock3 size={14} /> {preparing ? "Preparing..." : "Prepare timeline"}</button>{timeline.length > 0 && <button className="dashboard-primary-button" type="button" disabled={saving} onClick={() => onSave(true)}><Check size={14} /> {approved ? "Timeline approved" : "Approve timeline"}</button>}</div></div>{!timeline.length ? <div className="queue-empty"><Film size={18} /><span>Complete approved Google Flow jobs first, then prepare the timeline.</span></div> : <><div className="timeline-ruler"><span>00:00</span><span>Audio timing spine · {timeline.length} clips</span><span>{time(timeline[timeline.length - 1].endTimeSeconds)}</span></div><div className="timeline-list">{timeline.map((item) => <article className="timeline-item" key={item.id}><div className="timeline-item__number">SCENE {item.sceneNumber.toString().padStart(2, "0")}<strong>{time(item.startTimeSeconds)} – {time(item.endTimeSeconds)}</strong></div><div className="timeline-item__clip"><button type="button" onClick={() => void preview(item.clipUrl)}><Film size={16} /> Open clip</button><span>{item.clipUrl ? "Google Flow clip linked" : "Missing clip"}</span></div><div className="timeline-item__fields"><label><span>Speed</span><input type="number" min="0.25" max="3" step="0.05" value={item.speed} onChange={(event) => update(item.id, "speed", Number(event.target.value) || 1)} /></label><label><span>Transition</span><select value={item.transition} onChange={(event) => update(item.id, "transition", event.target.value)}><option>Invisible transition</option><option>Cut</option><option>Dissolve</option><option>Fade</option></select></label><label><span>Caption</span><input value={item.caption} onChange={(event) => update(item.id, "caption", event.target.value)} placeholder="Optional emotional caption" /></label><label><span>Sound effect</span><input value={item.soundEffect} onChange={(event) => update(item.id, "soundEffect", event.target.value)} placeholder="Silence, impact, ambience..." /></label></div></article>)}</div><button className="secondary-action-button timeline-save-button" type="button" disabled={saving} onClick={() => onSave(false)}><Save size={14} /> {saving ? "Saving..." : "Save timeline changes"}</button></>}</section>;
}
